//Get Commands
GET http://localhost:5000/api/Customer/Customers
###
GET http://localhost:5000/api/Customer/CustomerOrder/14
###
GET http://localhost:5000/api/Property
###
GET http://localhost:5000/api/Paper
###
GET http://localhost:5000/api/Order
###
GET http://localhost:5000/api/OrderEntry
###
//All commands have been formatted the same way so they should work
###
POST http://localhost:5000/api/Customer/create
Content-Type: application/json

{
  "name": "Johan Dober",
  "address": "123 where street",
  "phone": "12345678",
  "email": "e@e2.dk"
}
###
POST http://localhost:5000/api/Property/create
Content-Type: application/json

{
  "propertyName": "Test"
}

###
PATCH http://localhost:5000/api/Customer/update/14
Content-Type: application/json

{
  "name": "Janet Dober",
  "address": "123 where street",
  "phone": "12345678",
  "email": "e@e.dk"
}
###
DELETE http://localhost:5000/api/Customer/delete/
//deletes a customer based on the specified id