GET http://localhost:5000/
//gets a list of customers
###
POST http://localhost:5000/api/create
//creates a set customer value
###
PATCH http://localhost:5000/api/update/7
//updates a customer value based on the id provided
###
DELETE http://localhost:5000/api/delete/7
//deletes a customer based on the specified id